defaults:
  - preprocess: default
  - dataset: default
  - model: default
  - train: default
log_dir: ./logs
debug: false
ckpt: null # infer
input_dir: null # infer
output_dir: null # infer
model:
  proj_dim: 256
train:
  contrastive_temp: 0.07
  batch_size: 1
  filelist: /workspace/xcodec2n/filelists/0.1_train_filelist.json
  shuffle: true
  lambdas:
    lambda_contrast: 1.0
val:
  batch_size: 1
  filelist: /workspace/xcodec2n/filelists/val_filelist.json
  shuffle: true
hydra:
  output_subdir: hydra
  job:
    chdir: True
