trainer:
  default_root_dir: "/workspace/xcodec2n/outputs"
  accelerator: 'gpu'
  num_nodes: 1
  devices: 1
  max_epochs: 10
  precision: 16-mixed
  limit_val_batches: 20
  val_check_interval: 50 
  check_val_every_n_epoch: null
  num_sanity_val_steps: 0
  limit_train_batches: 100

# loss
lambdas:
  lambda_disc: 1.0
  lambda_feat_match_loss: 1.0
  lambda_mel_loss: 15.0
  lambda_adv: 1.0
  lambda_stft_loss: 1.0
  lambda_semantic_loss: 5
  lambda_perceptual_loss: 0
  lambda_contrast: 20.0

use_mel_loss: true
use_feat_match_loss: true
use_stft_loss: false

# optimizer
gen_optim_params:
  base_lr: 2.5e-4
  reference_batch_size: 12
  betas: [0.8, 0.9]

disc_optim_params:
  base_lr: 1.0e-4
  reference_batch_size: 12
  betas: [0.8, 0.9]

# 新增 contrastive 相关配置
contrastive_all_gather: false
contrastive_proj_dim: 256
# contrastive 温度已经在 cfg/default.yaml 中定义为 contrastive_temp: 0.07（或在 model 中 proj_dim）

gen_grad_clip: 1.0
disc_grad_clip: 1.0

# scheduler
gen_schedule_params:
  warmup_step: 10
  down_step: 400000
disc_schedule_params:
  warmup_step: 10
  down_step: 400000
  min_lr: 1.0e-5
  max_lr: 2.5e-4
